lang: de
name: Die Maschine träumt
title: Die Maschine träumt
description: Eine PB‑VRT / FountainAI Arbeit – Bühne, Bild und Klang im Quiet Frame
url: "https://fountain-coach.github.io"
baseurl: "/Die-Maschine-traeumt"
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
permalink: pretty
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

logo: /assets/img/HEADER.png
twitter:
  card: summary_large_image
